# Generated by Django 3.0.8 on 2020-07-17 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Alpha-2 Code')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('langId', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ISO 4217 Code')),
                ('symbol', models.CharField(max_length=8, verbose_name='examples: US$, R$, A$, C$')),
                ('name', models.CharField(max_length=128)),
                ('thousands_separator_symbol', models.CharField(max_length=1)),
                ('decimal_symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('desc', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(blank=True, max_length=128)),
                ('balance', models.FloatField(default=0.0)),
                ('se_short', models.CharField(max_length=32, verbose_name='Stock Exchange Short')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField(null=True)),
                ('subscription_expires_on', models.DateField(db_index=True, null=True)),
                ('subscription_renews_on', models.DateField(db_index=True, null=True)),
                ('pref_langId', models.CharField(max_length=8)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country')),
                ('pref_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userCustom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset_label', models.CharField(max_length=32)),
                ('asset_symbol', models.CharField(db_index=True, max_length=32)),
                ('amount', models.IntegerField()),
                ('started_on', models.DateTimeField(db_index=True)),
                ('s_unit_price', models.FloatField()),
                ('s_operational_cost', models.FloatField(default=0.0)),
                ('s_total_price', models.FloatField()),
                ('ended_on', models.DateTimeField(db_index=True, default=None, null=True)),
                ('e_unit_price', models.FloatField(default=None, null=True)),
                ('e_operational_cost', models.FloatField(default=None, null=True)),
                ('e_total_price', models.FloatField(default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.PositionType')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
        ),
    ]
