# Generated by Django 3.0.2 on 2020-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executed_on',
            field=models.DateTimeField(db_index=True),
        ),
    ]
