# Generated by Django 3.0.2 on 2020-03-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200301_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('se_short', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Stock Exchange Short')),
                ('se_name', models.CharField(db_index=True, max_length=128, verbose_name='Stock Exchange Name')),
                ('se_startTime', models.TimeField(verbose_name='Usual time the market starts')),
                ('se_endTime', models.TimeField(verbose_name='Usual time the market ends')),
                ('se_timezone', models.CharField(max_length=32, verbose_name='Timezone (TZ database name)')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('asset_symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('asset_label', models.CharField(max_length=32)),
                ('asset_name', models.CharField(max_length=128)),
                ('asset_currency', models.CharField(max_length=8)),
                ('asset_isException', models.BooleanField(default=False)),
                ('asset_lastTradeTime', models.CharField(db_index=True, max_length=32, null=True)),
                ('asset_price', models.FloatField(null=True)),
                ('asset_volatility', models.FloatField(null=True, verbose_name='Volatility percentage over last 10 days.')),
                ('asset_volume_avg', models.IntegerField(null=True, verbose_name='Volume average over last 10 days.')),
                ('stockExchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.StockExchange')),
            ],
        ),
    ]
