# Generated by Django 3.0.2 on 2020-03-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_asset_stockexchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='StockExchange',
        ),
    ]
