# Generated by Django 3.0.8 on 2020-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200814_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuprule',
            name='desc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='setuprule',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
    ]
