# Generated by Django 3.0.8 on 2020-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200814_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuprule',
            name='is_multi_interval',
            field=models.BooleanField(default=False, verbose_name='Is it possible to apply the same rule for morethan one time interval (s, d, 60m, 30m)'),
        ),
    ]
