# Generated by Django 3.0.2 on 2020-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200314_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='se_short',
            field=models.CharField(default='SAO', max_length=32, verbose_name='Stock Exchange Short'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operational_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
