# Generated by Django 3.0.8 on 2020-09-06 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_setuprule_is_multi_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(blank=True, max_length=128)),
                ('is_multi_interval', models.BooleanField(default=False, verbose_name='Is it possible to apply the same rule for morethan one time interval (s, d, 60m, 30m)')),
                ('rules_json', models.TextField()),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SetupRule',
        ),
    ]
