# Generated by Django 3.0.8 on 2020-09-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200906_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='rules_json',
        ),
        migrations.AddField(
            model_name='strategy',
            name='workspaces',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
