# Generated by Django 3.0.2 on 2020-03-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200329_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_symbol',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
