# Generated by Django 3.0.8 on 2020-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200907_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='workspaces',
        ),
        migrations.AddField(
            model_name='strategy',
            name='rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
