# Generated by Django 3.0.2 on 2020-03-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default='BRL', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
            preserve_default=False,
        ),
    ]
