# Generated by Django 3.0.8 on 2020-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200908_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='is_multi_interval',
        ),
        migrations.AddField(
            model_name='strategy',
            name='is_dinamic',
            field=models.BooleanField(default=False, verbose_name='Is it possible to apply the same rule for morethan one time interval (s, d, 60m, 30m)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is it public for other users?'),
        ),
    ]
