# Generated by Django 3.0.8 on 2020-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200908_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='is_dinamic',
        ),
        migrations.AddField(
            model_name='strategy',
            name='is_dynamic',
            field=models.BooleanField(default=False, verbose_name='Is it possible to apply the same rule for morethan one time interval (s, d, 60m, 30m)'),
        ),
    ]
