# Generated by Django 3.0.8 on 2020-09-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200909_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
