# Generated by Django 3.0.2 on 2020-03-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usercustom_pref_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country'),
            preserve_default=False,
        ),
    ]
