# Generated by Django 3.0.2 on 2020-03-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_currency_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(default='BRL', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
            preserve_default=False,
        ),
    ]
