# Generated by Django 3.0.8 on 2020-09-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200909_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='type',
            field=models.CharField(default='buy', max_length=32, verbose_name='buy or sell'),
            preserve_default=False,
        ),
    ]
