# Generated by Django 3.0.8 on 2020-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_strategy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='desc',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
