# Generated by Django 3.0.2 on 2020-03-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200329_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset_symbol', models.CharField(max_length=32)),
                ('first_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_transaction', to='app.Transaction')),
                ('last_transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_transaction', to='app.Transaction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Wallet')),
            ],
        ),
    ]
