# Generated by Django 3.0.2 on 2020-03-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200329_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='last_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_transaction', to='app.Transaction'),
        ),
    ]
