# Generated by Django 3.0.8 on 2020-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200912_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='is_dynamic',
            field=models.BooleanField(default=False, verbose_name='Logic type'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(max_length=8, verbose_name='buy or sell'),
        ),
    ]
