# Generated by Django 3.0.2 on 2020-04-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200329_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
