# Generated by Django 3.0.8 on 2020-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200913_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='desc',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
