# Generated by Django 3.0.8 on 2020-11-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200927_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='subscription_type',
            field=models.CharField(max_length=16, null=True, verbose_name='monthly/annual'),
        ),
    ]
