# Generated by Django 3.0.2 on 2020-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='operational_cost',
            new_name='s_operational_cost',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='total_price',
            new_name='s_total_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='unit_price',
            new_name='s_unit_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='executed_on',
            new_name='started_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='e_operational_cost',
            field=models.FloatField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='e_total_price',
            field=models.FloatField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='e_unit_price',
            field=models.FloatField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ended_on',
            field=models.DateTimeField(db_index=True, null=True, default=None),
        ),
    ]
