# Generated by Django 3.0.8 on 2020-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usercustom_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='subscription_type',
            field=models.CharField(default='monthly', max_length=16, verbose_name='monthly/annual'),
        ),
    ]
