# Generated by Django 3.0.2 on 2020-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200404_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
