# Generated by Django 3.0.8 on 2020-11-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201108_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='subscription_type',
        ),
    ]
