# Generated by Django 3.0.2 on 2020-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='decimal_symbol',
            field=models.CharField(default='.', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='thousands_separator_symbol',
            field=models.CharField(default=',', max_length=1),
            preserve_default=False,
        ),
    ]
