# Generated by Django 3.0.2 on 2020-04-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200419_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='is_default',
        ),
    ]
