# Generated by Django 3.0.2 on 2020-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_wallet_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='symbol',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='alpha-2 code'),
        ),
    ]
