# Generated by Django 3.1.3 on 2020-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_subscriptionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='stripe_customer_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
