# Generated by Django 3.1.3 on 2020-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_usercustom_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='subscription_status',
            field=models.CharField(default='undefined', max_length=16),
        ),
    ]
