# Generated by Django 3.0.2 on 2020-05-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='country',
            field=models.ForeignKey(default='BR', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country'),
            preserve_default=False,
        ),
    ]
