# Generated by Django 3.1.3 on 2020-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_usercustom_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='subscription_status',
            field=models.CharField(default='undefined', max_length=16),
        ),
    ]
