# Generated by Django 3.0.2 on 2020-05-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_wallet_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='symbol',
            new_name='code',
        ),
    ]
