# Generated by Django 3.1.3 on 2020-11-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_auto_20201110_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='pref_currency',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='pref_langId',
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userPrefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
