# Generated by Django 3.1.3 on 2020-11-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201114_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
