# Generated by Django 3.0.2 on 2020-05-17 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20200511_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Position',
        ),
        migrations.RenameModel(
            old_name='TransactionType',
            new_name='PositionType',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Alpha-2 Code'),
        ),
    ]
