# Generated by Django 3.0.2 on 2020-06-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200517_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_label',
            field=models.CharField(default='To Change', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.Wallet'),
        ),
    ]
