# Generated by Django 3.0.2 on 2020-06-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200620_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_label',
            new_name='label',
        ),
    ]
