# Generated by Django 3.0.2 on 2020-06-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200620_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='label',
        ),
    ]
