# Generated by Django 3.1.3 on 2020-12-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201115_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, db_index=True)),
                ('runs', models.IntegerField(default=1)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.strategy')),
            ],
        ),
    ]
