# Generated by Django 3.1.3 on 2020-12-10 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_strategyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyusage',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='app.strategy'),
        ),
        migrations.CreateModel(
            name='StrategyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('usage_last_7_days', models.IntegerField(default=1)),
                ('usage_last_14_days', models.IntegerField(default=1)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='strategyrating',
            index=models.Index(fields=['user', 'strategy'], name='app_strateg_user_id_fa3e64_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyrating',
            constraint=models.UniqueConstraint(fields=('user', 'strategy'), name='unique_rating'),
        ),
    ]
