# Generated by Django 3.0.2 on 2020-06-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_country_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='nationality',
        ),
    ]
