# Generated by Django 3.0.2 on 2020-06-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_usercustom_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='nationality',
            field=models.ForeignKey(default='BR', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country'),
            preserve_default=False,
        ),
    ]
