# Generated by Django 3.1.3 on 2020-12-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201210_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystats',
            name='strategy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app.strategy'),
        ),
    ]
