# Generated by Django 3.0.2 on 2020-06-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200623_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='subscription',
        ),
    ]
