# Generated by Django 3.0.2 on 2020-06-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_usercustom_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='subscription',
            field=models.ForeignKey(default='basic', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subscription'),
            preserve_default=False,
        ),
    ]
