# Generated by Django 3.1.3 on 2020-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20201210_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystats',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
