# Generated by Django 3.0.2 on 2020-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_usercustom_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
