# Generated by Django 3.0.2 on 2020-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_usercustom_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
