# Generated by Django 3.1.3 on 2020-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201211_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystats',
            old_name='rating',
            new_name='rating_avg',
        ),
        migrations.AddField(
            model_name='strategyrating',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategyrating',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategystats',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategystats',
            name='runs_last_14_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategystats',
            name='runs_last_7_days',
            field=models.IntegerField(default=0),
        ),
    ]
