# Generated by Django 3.0.2 on 2020-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_usercustom_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
