# Generated by Django 3.1.3 on 2020-12-13 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20201212_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyrating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
