# Generated by Django 3.0.2 on 2020-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_usercustom_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='asset_symbol',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
