# Generated by Django 3.1.3 on 2020-12-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201213_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyrating',
            old_name='is_favorite',
            new_name='is_saved',
        ),
        migrations.RenameField(
            model_name='strategystats',
            old_name='favorite_count',
            new_name='saved_count',
        ),
    ]
