# Generated by Django 3.0.2 on 2020-07-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200704_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='is_email_confirmed',
        ),
    ]
