# Generated by Django 3.1.3 on 2020-12-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201216_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystats',
            old_name='runs_last_7_days',
            new_name='runs_last_30_days',
        ),
    ]
