# Generated by Django 3.1.3 on 2020-12-21 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0037_auto_20201220_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystats',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
