# Generated by Django 3.0.8 on 2020-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_usercustom_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='subscription_renews_on',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
