# Generated by Django 3.0.8 on 2020-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_usercustom_subscription_renews_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='desc',
        ),
        migrations.AddField(
            model_name='subscription',
            name='label',
            field=models.CharField(default='Temp', max_length=32),
            preserve_default=False,
        ),
    ]
