# Generated by Django 3.1.3 on 2020-12-24 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_auto_20201222_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyrating',
            name='is_saved',
        ),
        migrations.CreateModel(
            name='StrategySaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='strategysaved',
            index=models.Index(fields=['user', 'strategy'], name='app_strateg_user_id_38a9fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategysaved',
            constraint=models.UniqueConstraint(fields=('user', 'strategy'), name='unique_saved_strategies'),
        ),
    ]
