# Generated by Django 3.1.3 on 2020-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20201224_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='tags',
            field=models.JSONField(default=[]),
        ),
    ]
