# Generated by Django 3.1.3 on 2020-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_strategy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='rules',
            field=models.JSONField(),
        ),
    ]
