# Generated by Django 3.1.3 on 2020-12-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20201231_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrating',
            name='review',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
