# Generated by Django 3.1.3 on 2021-01-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_strategyrating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyrating',
            name='review',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
