# Generated by Django 3.1.3 on 2021-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_strategy_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='links',
            field=models.JSONField(default=[]),
        ),
    ]
