# Generated by Django 3.1.3 on 2021-01-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210104_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='links',
            field=models.JSONField(default=[]),
        ),
    ]
