# Generated by Django 3.1.3 on 2021-01-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210105_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystats',
            name='strategy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='app.strategy'),
        ),
        migrations.AlterField(
            model_name='strategyusage',
            name='runs',
            field=models.IntegerField(default=0),
        ),
    ]
