# Generated by Django 3.1.3 on 2021-01-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20210107_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(db_index=True, max_length=8, verbose_name='buy or sell'),
        ),
    ]
