# Generated by Django 3.1.3 on 2021-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210107_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='links',
            field=models.JSONField(default=list),
        ),
    ]
