# Generated by Django 3.1.3 on 2021-02-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210201_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CollectionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('index', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collection')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.strategy')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='strategies',
            field=models.ManyToManyField(through='app.CollectionMembership', to='app.Strategy'),
        ),
    ]
