# Generated by Django 3.1.3 on 2021-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210203_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='sid',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
